# Generated by Django 3.2.14 on 2023-02-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_auto_20230210_2047"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
